# Generated by Django 2.2 on 2020-08-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='granted',
        ),
        migrations.AddField(
            model_name='wish',
            name='grantedwish',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='granted', to='wish.User'),
            preserve_default=False,
        ),
    ]
