# Generated by Django 2.2 on 2020-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_remove_wish_grantedwish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='grants',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
